name: test-service

on:
  push:
    branches:
      - '^2[0-9].[0-9]{1,2}-(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - 'master'
  pull_request:
    branches:
      - '^(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - '^2[0-9].[0-9]{1,2}-(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - 'master'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run a one-line script
        run: |
          echo Hello, Hyla!
          echo ${{ github.actor }} has pushed a change to Hyla.
          echo This code was committed by: ${{ github.event.commits[0].author.name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: find changed files
        id: changed-files
        run: |
          echo ::set-output name=CHANGED_FILES::$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

      - name: run checkstyle for changed files
        run: ./config/checkstyle/checkstyle.sh ${{ steps.changed-files.outputs.CHANGED_FILES }}

      - name: print analysis(remove)
        run: cat build/reports/checkstyle-analysis.sarif

      - name: compress sarif file
        id: compress
        run: |
          echo ::set-output name=compressed-sarif::$(gzip -c build/reports/checkstyle-analysis.sarif | base64 -w0)

      - name: publish analysis
        run: |
          curl -X POST --location "https://api.github.com/repos/${GITHUB_REPOSITORY}/code-scanning/sarifs" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{
          \"commit_sha\": \"${{ github.event.pull_request.head.sha }}\",
          \"ref\": \"refs/pull/${{ github.event.pull_request.number }}/head\",
          \"sarif\": \"${{ steps.compress.outputs.compressed-sarif }}\",
          \"tool_name\": \"checkstyle\"
          }"


